theme: jekyll-theme-minimal
title: Sarah's Fitnesse Blog
description: A blog to track the improvement to my fitnesse and overall health. Includes progress markers, tips, recipes, and general thoughts/feelings throughout.
Also - because I like playing on hard mode - I'm going to concurrently teach myself front end by making this site nicer - kind feedback on bugs or features welcome!
